@startuml Děkanát
left to right direction

'======== Actors ========
actor Děkanát
actor "Rozvrhová komise" as RK

'======== Use Cases ========
package "Modul rozvrhy" {
  Package Předměty {
    usecase "Vytvořit nový předmět" as UCP1
    usecase "Upravit existující předmět" as UCP2
    usecase "Smazat existující předmět" as UCP3
    usecase "Zobrazit předměty" as UCP3
  }

'======== Use case links ========
Děkanát --> UCP1
Děkanát --> UCP2
Děkanát --> UCP3

}